### ISSUE TITLE
gui-builder: opening and closing a menu repeatedly causes a segfault

### ISSUE THREAD

**Issue by SmallJoker** [texus/TGUI#197]
TGUI version: ae3049891 (current 1.x branch)
Compiled TGUI with SFML 2.5.1:

```sh
cmake -S . -B build \
	-DTGUI_BACKEND=SFML_GRAPHICS
cmake --build build
```

After opening and closing the menu by pressing onto it, the application crashes. However, it seems that the crash happens within TGUI itself, so this might be a deeper issue.

```C++
(gdb) bt
#0  0x00005555555a684c in void std::vector<tgui::String, std::allocator<tgui::String> >::_M_realloc_insert<tgui::String const&>(__gnu_cxx::__normal_iterator<tgui::String*, std::vector<tgui::String, std::allocator<tgui::String> > >, tgui::String const&) ()
#1  0x00007ffff7e0aafe in tgui::MenuBar::leftMouseReleasedOnMenu() ()
   from xxx/TGUI/build/lib/libtgui.so.1.0.0
#2  0x00007ffff7e2aee9 in tgui::Container::remove(std::shared_ptr<tgui::Widget> const&) ()
   from xxx/TGUI/build/lib/libtgui.so.1.0.0
#3  0x00007ffff7df146a in tgui::MenuBar::closeMenu() ()
   from xxx/TGUI/build/lib/libtgui.so.1.0.0
#4  0x00007ffff7e0aa72 in tgui::MenuBar::leftMouseReleasedOnMenu() ()
   from xxx/TGUI/build/lib/libtgui.so.1.0.0
#5  0x00007ffff7e28a42 in tgui::Container::processMouseReleaseEvent(tgui::Event::MouseButton, tgui::Vector2<float>) () from xxx/TGUI/build/lib/libtgui.so.1.0.0
#6  0x00007ffff7d4347e in tgui::BackendGui::handleEvent(tgui::Event) ()
   from xxx/TGUI/build/lib/libtgui.so.1.0.0
#7  0x000055555563769d in GuiBuilder::mainLoop() ()
#8  0x00005555555836c8 in main ()
```

**Comment by texus** [comment]
Thanks for reporting. It looks like the change in https://github.com/texus/TGUI/commit/c4923a374c23e3e6a98cb7efa990158ae12f8e3c caused a condition that was previously impossible (there was even an assert for this at the crash location).
It should be fixed now.

**Comment by SmallJoker** [comment]
Thanks for the blazingly fast fix! Much appreciated.
